package com.get.Hibernate;
// default package
// Generated 17-Nov-2016 14:58:20 by Hibernate Tools 5.2.0.Beta1

/**
 * HkUserRssSub generated by hbm2java
 */
public class HkUserRssSub implements java.io.Serializable {

	private HkUserRssSubId id;

	public HkUserRssSub() {
	}

	public HkUserRssSub(HkUserRssSubId id) {
		this.id = id;
	}

	public HkUserRssSubId getId() {
		return this.id;
	}

	public void setId(HkUserRssSubId id) {
		this.id = id;
	}

}
