package com.get.Hibernate;
// default package
// Generated 17-Nov-2016 14:58:20 by Hibernate Tools 5.2.0.Beta1

/**
 * HkUser generated by hbm2java
 */
public class HkUser implements java.io.Serializable {

	private HkUserId id;

	public HkUser() {
	}

	public HkUser(HkUserId id) {
		this.id = id;
	}

	public HkUserId getId() {
		return this.id;
	}

	public void setId(HkUserId id) {
		this.id = id;
	}

}
