package com.get.Hibernate;
// default package
// Generated 17-Nov-2016 14:58:20 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * StockDetailId generated by hbm2java
 */
public class StockDetailId implements java.io.Serializable {

	private String stockId;
	private Date stockDate;

	public StockDetailId() {
	}

	public StockDetailId(String stockId, Date stockDate) {
		this.stockId = stockId;
		this.stockDate = stockDate;
	}

	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public Date getStockDate() {
		return this.stockDate;
	}

	public void setStockDate(Date stockDate) {
		this.stockDate = stockDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockDetailId))
			return false;
		StockDetailId castOther = (StockDetailId) other;

		return ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
				&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())))
				&& ((this.getStockDate() == castOther.getStockDate()) || (this.getStockDate() != null
						&& castOther.getStockDate() != null && this.getStockDate().equals(castOther.getStockDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		result = 37 * result + (getStockDate() == null ? 0 : this.getStockDate().hashCode());
		return result;
	}

}
